name: build-and-test

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore EvenSteven.App.slnx --nologo

      - name: Build
        run: dotnet build EvenSteven.App.slnx --configuration Debug --no-restore --nologo

      - name: Style
        run: dotnet format EvenSteven.App.slnx --verify-no-changes --no-restore

      - name: Test
        run: dotnet test --project tests/EvenSteven.RepositoryTests/EvenSteven.RepositoryTests.csproj --configuration Debug